body:
  - type: markdown
    attributes:
      value: |
        ### Enter your question above in the title
  - type: input
    id: hr-source
    attributes:
      label: "Source of the question"
      placeholder: Company Name, LeetCode, etc.
    validations:
      required: false

  - type: textarea
    id: hr-additional-info
    attributes:
      label: "Additional Info"
      placeholder: "Provide any additional information if needed."
    validations:
      required: false
