title: "Type your question here..."
body:
  - type: input
    id: source
    attributes:
      label: "Source of the question"
      description: Enter 'NA' if not known
      placeholder: "'Company Name', 'LeetCode', etc."
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: "Additional Information"
      placeholder: "Provide any additional information or context (optional)."
    validations:
      required: false
