title: "Type your question here..."
body:
  - type: input
    id: source
    attributes:
      label: Source
      description: "Provide the source of the question."
      placeholder: "E.g., 'Company name', 'LeetCode', etc."
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      placeholder: "Provide any additional information if necessary."
    validations:
      required: false
