title: "Type your question here..."
body:
  - type: input
    id: source
    attributes:
      label: "Source of the question:"
      placeholder: "'Company Name', 'LeetCode', etc."
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      placeholder: "Provide any additional information if necessary."
    validations:
      required: false
