title: "Type your question here..."
body:
  - type: input
    id: technical-source
    attributes:
      label: "Source of the question"
      description: "Example: Company Name, LeetCode, etc."
      placeholder: Enter 'NA' if not known
    validations:
      required: true

  - type: textarea
    id: technical-additional-info
    attributes:
      label: "Additional Information"
      placeholder: "Provide any additional information if necessary."
    validations:
      required: false
