categories:
  - id: technical-ques
    label: Technical Ques
    body:
      - type: textarea
        id: question
        attributes:
          label: Question
          description: "Enter your technical question."
          value: |
            Describe your question here.
          render: text
        validations:
          required: true

      - type: textarea
        id: source
        attributes:
          label: Source
          description: "Provide the source or reference for your question."
          value: |
            Add your source or reference here.
          render: text
        validations:
          required: true

      - type: textarea
        id: additional-info
        attributes:
          label: Additional Information
          description: "Include any other relevant details if necessary."
          value: |
            Add any extra details here.
          render: text

  - id: Test
    label: Test
    body:
      - type: textarea
        id: title
        attributes:
          label: Resource Title
          description: "Provide the title of the resource."
          value: |
            Enter the title here.
          render: text
        validations:
          required: true

      - type: textarea
        id: resource-link
        attributes:
          label: Resource
          description: "Provide the link or details of the resource."
          value: |
            Add the resource link or details here.
          render: text
        validations:
          required: true
