body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: "Enter your technical question."
      value: |
        Describe your question here.
      render: text
    validations:
      required: true

  - type: textarea
    id: source
    attributes:
      label: Source
      description: "Provide the source or reference for your question."
      value: |
        Add your source or reference here.
      render: text
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: "Include any other relevant details if necessary."
      value: |
        Add any extra details here.
      render: text

  - type: markdown
    attributes:
      value: "## Thank you for contributing to our project!"
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
